*&---------------------------------------------------------------------*
*& Report Z_TESTREPORT
*&---------------------------------------------------------------------*
*& This report demonstrates various ABAP reporting capabilities:
*& - Selection Screens (Parameters, Select-Options, Blocks)
*& - Event Handling (Initialization, Validation, Processing)
*& - Dynamic Screen Modification
*& - Data Processing
*& - List Output Formatting (Colors, Icons)
*&---------------------------------------------------------------------*
REPORT z_testreport MESSAGE-ID 00.
INCLUDE <icon>.

*----------------------------------------------------------------------*
* Data Declarations
*----------------------------------------------------------------------*
TYPES: BEGIN OF ty_data,
         id    TYPE i,
         name  TYPE string,
         value TYPE p LENGTH 8 DECIMALS 2,
         date  TYPE d,
       END OF ty_data.

DATA: gt_data TYPE TABLE OF ty_data,
      gs_data TYPE ty_data.

*----------------------------------------------------------------------*
* Selection Screen
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-001.
PARAMETERS: p_show AS CHECKBOX DEFAULT 'X' USER-COMMAND ucomm.
PARAMETERS: p_max  TYPE i DEFAULT 10 MODIF ID gr1.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-002.
SELECT-OPTIONS: s_date FOR sy-datum.
PARAMETERS: r_opt1 RADIOBUTTON GROUP rb1 DEFAULT 'X',
              r_opt2 RADIOBUTTON GROUP rb1.
SELECTION-SCREEN END OF BLOCK b2.

*----------------------------------------------------------------------*
* Initialization
*----------------------------------------------------------------------*
INITIALIZATION.

  " Default date range: Last 30 days
  s_date-sign = 'I'.
  s_date-option = 'BT'.
  s_date-low = sy-datum - 30.
  s_date-high = sy-datum.
  APPEND s_date.

*----------------------------------------------------------------------*
* At Selection Screen Output (PBO of Selection Screen)
*----------------------------------------------------------------------*
AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    " Hide p_max if p_show is unchecked
    IF p_show = ' ' AND screen-group1 = 'GR1'.
      screen-active = '0'.
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.

*----------------------------------------------------------------------*
* At Selection Screen (Validation)
*----------------------------------------------------------------------*
AT SELECTION-SCREEN.
  IF r_opt2 = 'X' AND s_date IS INITIAL.
    MESSAGE 'Please provide a date range when Option 2 is selected.' TYPE 'W'.
  ENDIF.

*----------------------------------------------------------------------*
* Start of Selection (Main Processing)
*----------------------------------------------------------------------*
START-OF-SELECTION.
  PERFORM get_data.
  PERFORM process_data.

*----------------------------------------------------------------------*
* End of Selection (Output)
*----------------------------------------------------------------------*
END-OF-SELECTION.
  PERFORM display_output.

*----------------------------------------------------------------------*
* Top of Page
*----------------------------------------------------------------------*
TOP-OF-PAGE.
  WRITE: / 'Report generated by:', sy-uname, 'on', sy-datum.
  ULINE.

*&---------------------------------------------------------------------*
*&      Form  GET_DATA
*&---------------------------------------------------------------------*
FORM get_data.
  DO p_max TIMES.
    gs_data-id    = sy-index.
    gs_data-name  = |Items { sy-index }|.
    gs_data-value = sy-index * 100 / 3. " Random calculation
    gs_data-date  = sy-datum - sy-index.
    APPEND gs_data TO gt_data.
  ENDDO.
ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  PROCESS_DATA
*&---------------------------------------------------------------------*
FORM process_data.
  IF r_opt2 = 'X'.
    DELETE gt_data WHERE date NOT IN s_date.
  ENDIF.
ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  DISPLAY_OUTPUT
*&---------------------------------------------------------------------*
FORM display_output.
  IF gt_data IS INITIAL.
    WRITE: / 'No data found matching criteria.' COLOR COL_NEGATIVE.
    RETURN.
  ENDIF.

  " Header
  FORMAT COLOR COL_HEADING INTENSIFIED ON.
  WRITE: / 'St',
         5 'ID',
         15 'Name',
         40 'Value',
         60 'Date',
         75 'Trend'.
  ULINE.
  FORMAT COLOR OFF.

  LOOP AT gt_data INTO gs_data.
    " Dynamic row background based on ID parity for zebra striping effect
    IF sy-tabix MOD 2 = 0.
      FORMAT COLOR COL_NORMAL INTENSIFIED OFF.
    ELSE.
      FORMAT COLOR COL_BACKGROUND INTENSIFIED OFF. " Standard background
    ENDIF.

    " Status Icon
    IF gs_data-value > 200.
      WRITE: / icon_led_red AS ICON.
    ELSEIF gs_data-value > 100.
      WRITE: / icon_led_yellow AS ICON.
    ELSE.
      WRITE: / icon_led_green AS ICON.
    ENDIF.

    " Data Fields
    WRITE: 5 gs_data-id COLOR COL_KEY INTENSIFIED OFF,
           15 gs_data-name.

    " Highlight Value Field
    IF gs_data-value > 200.
      WRITE: 40 gs_data-value CURRENCY 'EUR' COLOR COL_NEGATIVE INTENSIFIED OFF.
    ELSEIF gs_data-value > 100.
      WRITE: 40 gs_data-value CURRENCY 'EUR' COLOR COL_TOTAL INTENSIFIED OFF.
    ELSE.
      WRITE: 40 gs_data-value CURRENCY 'EUR' COLOR COL_POSITIVE INTENSIFIED OFF.
    ENDIF.

    WRITE: 60 gs_data-date.

    " Trend Icon
    IF gs_data-value > 150.
      WRITE: 75 icon_trend_up AS ICON.
    ELSE.
      WRITE: 75 icon_trend_down AS ICON.
    ENDIF.

    FORMAT COLOR OFF.
  ENDLOOP.
ENDFORM.
